# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auction.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rauction.proto\x12\x07\x61uction\"\x1e\n\rCreateRequest\x12\r\n\x05items\x18\x01 \x03(\t\"\x10\n\x0e\x43reateResponse\";\n\nBidRequest\x12\x0e\n\x06\x62idder\x18\x01 \x01(\t\x12\x0e\n\x06\x62undle\x18\x02 \x03(\t\x12\r\n\x05value\x18\x03 \x01(\x01\"\r\n\x0b\x42idResponse\"\x0e\n\x0c\x43loseRequest\"\x0f\n\rCloseResponse\"\x0e\n\x0cQueryRequest\".\n\rQueryResponse\x12\x0e\n\x06winner\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x32\xe6\x01\n\x07\x41uction\x12\x39\n\x06\x43reate\x12\x16.auction.CreateRequest\x1a\x17.auction.CreateResponse\x12\x30\n\x03\x42id\x12\x13.auction.BidRequest\x1a\x14.auction.BidResponse\x12\x36\n\x05\x43lose\x12\x15.auction.CloseRequest\x1a\x16.auction.CloseResponse\x12\x36\n\x05Query\x12\x15.auction.QueryRequest\x1a\x16.auction.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEREQUEST']._serialized_start=26
  _globals['_CREATEREQUEST']._serialized_end=56
  _globals['_CREATERESPONSE']._serialized_start=58
  _globals['_CREATERESPONSE']._serialized_end=74
  _globals['_BIDREQUEST']._serialized_start=76
  _globals['_BIDREQUEST']._serialized_end=135
  _globals['_BIDRESPONSE']._serialized_start=137
  _globals['_BIDRESPONSE']._serialized_end=150
  _globals['_CLOSEREQUEST']._serialized_start=152
  _globals['_CLOSEREQUEST']._serialized_end=166
  _globals['_CLOSERESPONSE']._serialized_start=168
  _globals['_CLOSERESPONSE']._serialized_end=183
  _globals['_QUERYREQUEST']._serialized_start=185
  _globals['_QUERYREQUEST']._serialized_end=199
  _globals['_QUERYRESPONSE']._serialized_start=201
  _globals['_QUERYRESPONSE']._serialized_end=247
  _globals['_AUCTION']._serialized_start=250
  _globals['_AUCTION']._serialized_end=480
# @@protoc_insertion_point(module_scope)
